### ISSUE TITLE
Pytorch Version

### ISSUE THREAD

**Issue by ttaa9** [VinAIResearch/DSW#1]
Hi! Thank you for releasing the code for such an interesting project.

I noticed your code expects an older version of pytorch. Would you consider a version that works with a newer pytorch (e.g., on a different branch)?

**Comment by khainb** [comment]
Thank you for your interest in our project. The code can work with newer versions of PyTorch since it requires only basic classes and functions. I have run a quick test with PyTorch 1.6 and the code still runs well. Again, thank you for the question, and feel free to ask if you have other questions.

**Comment by ttaa9** [comment]
Hi @khainb, thanks so much for looking at this.

Actually, I had an issue with python 3.8, pytorch 1.8.1, and cuda 10.1. At first, I got a couple errors, which were easy to solve (just changing the BCELoss label input to float and squeezing the `y_fake`s).

But then, when I run `python main.py --model-type DSWD --dataset CIFAR --datadir /w/272/taumen/data/`, I get the following error:
 ```
Traceback (most recent call last):
  File "main.py", line 311, in <module>
    main()
  File "main.py", line 293, in main
    loss.backward()
  File "/w/272/taumen/conda_envs/dswd2/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/w/272/taumen/conda_envs/dswd2/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

Changing the `ReLU/LeakyReLU`s to not be in-place does not solve the issue.

**Comment by khainb** [comment]
> Hi @khainb, thanks so much for looking at this.
> 
> Actually, I had an issue with python 3.8, pytorch 1.8.1, and cuda 10.1. At first, I got a couple errors, which were easy to solve (just changing the BCELoss label input to float and squeezing the `y_fake`s).
> 
> But then, when I run `python main.py --model-type DSWD --dataset CIFAR --datadir /w/272/taumen/data/`, I get the following error:
> 
> ```
> Traceback (most recent call last):
>  File "main.py", line 311, in <module>
>    main()
>  File "main.py", line 293, in main
>    loss.backward()
>  File "/w/272/taumen/conda_envs/dswd2/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
>    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>  File "/w/272/taumen/conda_envs/dswd2/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
>    Variable._execution_engine.run_backward(
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> ```
> 
> Changing the `ReLU/LeakyReLU`s to not be in-place does not solve the issue.

Hi, I turned off the "retain-graph" mode and it worked. Please see the code below:
```
label = torch.full((minibatch.shape[0],1), 1,dtype=torch.float32, device=self.device)
criterion = nn.BCELoss()
data = minibatch.to(self.device)
z_prior = rand_dist((data.shape[0], self.latent_size)).to(self.device)
data_fake = self.decoder(z_prior)
y_data, _ = discriminator(data.detach())
errD_real = criterion(y_data, label)
optimizer.zero_grad()
errD_real.backward()
optimizer.step()
y_fake, _ = discriminator(data_fake.detach())
label.fill_(0)
errD_fake = criterion(y_fake, label)
optimizer.zero_grad()
errD_fake.backward()
optimizer.step()

_, data = discriminator(data)
_, data_fake = discriminator(data_fake)
```
Thank you for the question. Please feel free to ask if there are other issues.

**Comment by ttaa9** [comment]
Thanks very much!
